USE data_job_market_db;

INSERT INTO skills
(skill_name)
VALUES
('Advanced Excel'),
('Excel'),
('Power BI'),
('Analytical Thinking'),
('Data Manipulation'),
('Database Knowledge'),
('Intermediate English'),
('Information Management'),
('PowerPoint'),
('Communication Skills'),
('Organization'),
('Proactivity'),
('Curiosity'),
('Collaboration'),
('Problem Solving'),
('Results-Oriented Mindset'),
('Project Ownership'),
('SQL'),
('Python'),
('Data Analysis'),
('Data Visualization'),
('Fraud Prevention'),
('Risk Analysis'),
('Financial Services Knowledge'),
('Attention to Detail'),
('Data-Driven Insights'),
('R'),
('Statistics'),
('Data Modeling'),
('Exploratory Data Analysis'),
('Business Indicators'),
('Power Query'),
('M Language'),
('DAX'),
('Business Intelligence'),
('Amazon Redshift'),
('BigQuery'),
('Data Storytelling'),
('Pandas'),
('ETL/ELT'),
('Analytics Automation'),
('Web Analytics'),
('Digital Marketing Analytics'),
('Google Analytics'),
('GA4'),
('Looker Studio'),
('Google Cloud Platform'),
('Agile Methodologies'),
('Digital Media Metrics'),
('Power Apps'),
('Power Automate'),
('Finance Knowledge'),
('Alteryx'),
('Structured Databases'),
('Unstructured Databases'),
('Spotfire'),
('Grafana'),
('Elasticsearch'),
('OpenSearch'),
('KQL'),
('LDAP'),
('API Integration'),
('Prometheus'),
('Reporting Analysis'),
('Quantitative Analysis'),
('Statistical Methods'),
('Strategic Thinking'),
('Stakeholder Management'),
('Google Sheets'),
('Google Slides'),
('Tableau'),
('Databricks'),
('Market Intelligence'),
('Data Extraction'),
('Star Schema Data Modeling'),
('Database Relationships'),
('Data Structures'),
('GitHub Version Control'),
('Query Optimization'),
('Data Pipeline Architecture'),
('Looker'),
('Statistics Fundamentals'),
('Pattern Recognition'),
('Trend Analysis'),
('Executive Communication'),
('Actionable Insights'),
('SQL Server'),
('Stored Procedures'),
('Views'),
('Triggers'),
('SSIS'),
('Reporting'),
('Consulting Skills'),
('Data Transformation'),
('Analytical Databases'),
('Business Decision Support'),
('Data Quality Validation'),
('Payment Methods Knowledge'),
('Fraud Analysis'),
('Digital Projects'),
('Growth Initiatives'),
('Mobile Applications'),
('E-Commerce Analytics'),
('A/B Testing'),
('CRO'),
('OKRs'),
('Business Metrics'),
('Executive Reporting'),
('Intermediate Spanish');